#TODO: Provide instructions for modpack devs.
---
<<<<<<< Updated upstream
ModPackConfigName: null
ModPackConfigVersion: 0
=======
ModPackConfigName: "Astrocraft"
ModPackConfigVersion: 1
>>>>>>> Stashed changes
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "Block Test"
Overworld:
  PresetName: null
  DimensionId: 9
  ShowInWorldCreationGUI: false
  LowestSupportedModPackConfigVersion: 1
  RemoveOnUpdate: false
  Seed: ""
<<<<<<< Updated upstream
  GameType: "Creative"
  BonusChest: false
  AllowCheats: true
=======
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
>>>>>>> Stashed changes
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "DIRT"
    PortalColor: "Default"
    PortalParticleType: "portal"
    PortalMobType: "villager"
    PortalMobSpawnChance: 2000
    IsOTGPlus: true
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: true
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 128
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: false
    SpawnPointX: 0
    SpawnPointY: 0
    SpawnPointZ: 0
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: false
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: false
    DoTileDrops: true
    DoWeatherCycle: false
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 10
    SpectatorsGenerateChunks: true
Dimensions: []